//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public int DirectoryId { get; set; }
        public string Name { get; set; }
        public int ParentId { get; set; }
        public int DepartmentId { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public int LastModifiedByUserId { get; set; }
        public bool IsDelete { get; set; }
        public int ModuleId { get; set; }
    }
}
