//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProcess
    {
        public int Id { get; set; }
        public int OrderIndex { get; set; }
        public int RelatedId { get; set; }
        public int TaskType { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    }
}
