//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPerform
    {
        public int PerformId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UserList { get; set; }
        public System.DateTime FinishedOnDate { get; set; }
        public int TaskType { get; set; }
        public int PriorityLevel { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public int UpdatedByUserId { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
        public int Status { get; set; }
        public int RelatedDocumentId { get; set; }
        public int IsFinished { get; set; }
        public int ModuleId { get; set; }
    }
}
