//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseUnit
    {
        public int EnterpriseUnitId { get; set; }
        public string Name { get; set; }
        public int BusinessTypeId { get; set; }
        public string TaxCode { get; set; }
        public string AgencyCode { get; set; }
        public string BusinessCode { get; set; }
        public string BusinessRegisteredCode { get; set; }
        public string RegisteredAddress { get; set; }
        public string ActualAddress { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Note { get; set; }
    }
}
