//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_ReceivedDocument_File
    {
        public int ReceivedDocumentId { get; set; }
        public int FileId { get; set; }
        public bool IsOriginal { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    }
}
