//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMessage
    {
        public int MessageId { get; set; }
        public string Title { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int ModuleId { get; set; }
        public System.DateTime Deadline { get; set; }
        public int Status { get; set; }
        public int TaskType { get; set; }
        public int UserId { get; set; }
        public int RelatedId { get; set; }
        public bool IsMyTask { get; set; }
    }
}
